# Generated by Django 5.2.8 on 2025-11-27 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
