# Generated by Django 5.2.8 on 2025-11-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_rename_added_at_favorite_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
